### ISSUE TITLE
2021-04-02 ~ 2021-04-04 계획

### ISSUE THREAD

**Issue by juunini** [CodeSoom/project-spring-1-juunini#2]
- [x] gradle 프로젝트를 생성하여 기반을 마련한다.
- [x] 스프링을 설치한다.
- [ ] AWS lambda 에서 사용할 수 있도록 세팅한다.
    - https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html
    - AWS lambda를 이용해 서버리스 엔드포인트를 구축할 수 있다.
    - main 브랜치에 merge 될 때 자동으로 배포되도록 세팅한다.

**Comment by hannut91** [comment]
돌아왔군요 ㅎㅎ 어떤 서비스인지 궁금합니다!
